AWSTemplateFormatVersion: "2010-09-09"
Description: AWS SAM template for the AWS::Lightsail::Container resource type

Resources:
  ThhisLightsailContainer:
    Type: AWS::Lightsail::Container
    Properties: 
      ContainerServiceDeployment: 
        Containers: 
          - ContainerName: "kaczor-container"
            Image: "nginx:latest"
            Ports: 
              - Port: "80"
                Protocol: "HTTP" 
        PublicEndpoint:
          ContainerName: "kaczor-container"
          ContainerPort: 80
          HealthCheckConfig: 
            Path: "/"
            SuccessCodes: "200"
      IsDisabled: false
      Power: nano
      Scale: 1
      ServiceName: "ponnny-service"